name: budgie
description: A personal finance management app.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # State Management
  provider: ^6.1.5
  get_it: ^7.6.4

  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  google_sign_in: ^6.2.1

  # Background Processing
  workmanager: ^0.6.0

  # UI & Responsive Design
  flutter_screenutil: ^5.9.3

  fl_chart: ^0.65.0
  intl: ^0.20.2

  # Local Storage
  drift: ^2.27.0
  sqlite3_flutter_libs: ^0.5.18
  path_provider: ^2.1.1
  path: ^1.8.3

  # Connectivity
  connectivity_plus: ^6.0.3
  uuid: ^4.5.1

  # Permissions
  permission_handler: ^11.2.0

  # API and Network
  http: ^1.2.1
  dio: ^5.4.3+1

  # TensorFlow Lite for machine learning inference
  tflite_flutter: ^0.11.0

  # Local Notifications
  flutter_local_notifications: ^19.2.1
  flutter_background: ^1.3.0
  timezone: ^0.10.0
  shared_preferences: ^2.5.3
  sign_in_with_apple: ^7.0.1
  crypto: ^3.0.6
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  drift_dev: ^2.16.0
  build_runner: ^2.4.9
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/models/
    - assets/models/classifier/

  fonts:
    - family: Lexend
      fonts:
        - asset: assets/fonts/Lexend-Regular.ttf
        - asset: assets/fonts/Lexend-Light.ttf
          weight: 300
        - asset: assets/fonts/Lexend-Medium.ttf
          weight: 500
        - asset: assets/fonts/Lexend-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Lexend-Bold.ttf
          weight: 700






